jwt:
  secretKey: mp8Ebz3EWNMudBkMh52Q5gQA5aFlC+yxr2Ns4I5VIvW+b+BgopSx8999Nj0Cm9PNl1MMdVS/mdRf

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh